---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - patchOS
    - reboot-server

- hosts: primary
  become: yes
  gather_facts: true
  roles:
    - elastic-cloud-enterprise
  vars:
    ece_primary: true

- hosts: director_coordinator
  become: yes
  roles:
    - elastic-cloud-enterprise
  vars:
    ece_roles: [director, coordinator, proxy]

- hosts: allocator
  become: yes
  roles:
    - elastic-cloud-enterprise
  vars:
    ece_roles: [allocator]
